# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4449111feee57e3688a2cba623d5acd4d291d8e4c5419bf69d5ff84b1235ea34c2205683dc704cc6504cfda4c32fbbd5f943e667565b4feb196871cae06b0ac

test:
  secret_key_base: 3793e7eb16425d0a95f64ad285e233d12503613f45573ee4500606939c8222142c838f252e05fdc68f494d6aa799a2c0caf76b4fbd4671559f03ab88950d7dfa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
